version: 2.1
orbs:
  node: circleci/node@3.0.0
  discord: antonioned/discord@0.1.0

workflows:
  node-tests:
    jobs:
      - node/test
      - discord/status: 
          webhook: "${DISCORD_STATUS_WEBHOOK}"
# I dont think this will work but I want to see so lets find out
