# I dont think this will work but I want to see so lets find out
version: 2.1
orbs:
  node: circleci/node@3.0.0
  discord: antonioned/discord@0.1.0
  
jobs: 
  comma-test: 
    executor: node/default
    steps: 
      - checkout
      - node/install-npm
      - 
        node/install-packages: 
          app-dir: ~/project/
          cache-path: node_modules
          override-ci-command: "npm i"
      - 
        run: 
          command: "npm test"
          name: "Test comma"
          working_directory: ~/project/
      - 
        discord/status: 
          webhook: "${DISCORD_STATUS_WEBHOOK}"
    working_directory: ~/project
    
workflows:
  node-tests:
    jobs:
      - comma-test
